### ISSUE TITLE
Conflict with fastify-static 4.2.0 and higher

### ISSUE THREAD

**Issue by user-7f7c2b9bc9e03070** [corsicanec82/fastify-method-override#13]
Fastify hexlet boilerplate with fastify-static ^4.2.0 starts and immediately stops without any errors

**Comment by corsicanec82** [comment]
The problem has already been identified, probably today I will publish a new version with a fix. Thank you for notification.

**Comment by corsicanec82** [comment]
The new version of the plugin 1.5.6 with a bug fix has already been published. Enjoy using the plugin.
