### ISSUE TITLE
Weird behaviour with native validation

### ISSUE THREAD

**Issue by felixcatto** [corsicanec82/fastify-method-override#5]
It seems that default validation through "schema" property doesn't work when we use this plugin. The validation just doesn't run at all.

<pre>
import fastify from 'fastify';
import fastifyFormbody from 'fastify-formbody';
import fastifyMethodOverride from 'fastify-method-override';

describe('requests', () => {
  let server;

  beforeAll(() => {
    server = fastify();
    server.register(fastifyFormbody);
    server.register(fastifyMethodOverride);
    server.put(
      '/',
      {
        schema: {
          body: {
            type: 'object',
            required: ['title'],
            properties: {
              title: { type: 'string' },
            },
          },
        },
      },
      (request, reply) => {
        reply.send();
      }
    );
  });

  it('PUT 400', async () => {
    const res = await server.inject({
      method: 'POST',
      url: '/',
      payload: { _method: 'PUT' },
    });
    expect(res.statusCode).toBe(400); 
    <b>
    // expect 400 because no required "title" property
    // but got 200 OK</b>
  });

  afterAll(() => {
    server.close();
  });
});
</pre>

UPD: i ended up writing own validation prehandler, so it's not a problem anymore, at least for me :)

**Comment by corsicanec82** [comment]
I will be working on this issue shortly. Thank.

**Comment by corsicanec82** [comment]
I will be working on this issue shortly. Thank.

**Comment by corsicanec82** [comment]
If you are having trouble using the plugin, you can use the [fastify-method-override-wrapper](https://github.com/corsicanec82/fastify-method-override-wrapper) library.
